development:
  sessions:
    default:
      database: db1
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: db1
      hosts:
        - localhost:27017
        # specs don't like being run on a replica set (3 mongods on the same machine) - failures due to timing
        # - localhost:27018
        # - localhost:27019
        # - localhost:27020
      options:
        consistency: :strong
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: db1
      hosts:
        - user1.user1-db.1.mongodbdns.com:27000
        - user1.user1-db.1.mongodbdns.com:27000
        - user1.user1-db.1.mongodbdns.com:27000
      username: user1
      password: mypass
      options:
        consistency: :strong
  options:
    identity_map_enabled: true

staging:
  sessions:
    default:
      database: db1
      hosts:
        - shab1.staging.c66.me:27017
      username: user1
      password: mypass
      options:
        consistency: :strong
  options:
    identity_map_enabled: true

# staging:
#   sessions:
#     default:
#       database: db1
#       hosts:
#         - ff.mongohq.com:10078
#       username: user1
#       password: mypass
#       options:
#         consistency: :strong
#   options:
#     identity_map_enabled: true

  # # Configure available database sessions. (required)
  # sessions:
  #   # Defines the default session. (required)
  #   default:
  #     # Defines the name of the default database that Mongoid can connect to.
  #     # (required).
  #     # database: db1
  #     # Provides the hosts the default session can connect to. Must be an array
  #     # of host:port pairs. (required)
  #     hosts:

